theme = "tale-hugo"
baseURL = "https://optimaldigression.com/"
languageCode = "en-us"
title = "Optimal Digression"

googleAnalytics= "UA-131475495-1"
summaryLength= 30
disqusShortname= "disqus_wOjK3CSAmn"
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
