theme = "tale-hugo"
baseURL = "http://optimaldigression.com/"
languageCode = "en-us"
title = "Optimal Digression"

highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
