---
title: Build something that matters.
author: Austin Armstrong
date: '2018-12-14'
slug: build-something-that-matters-in-R
categories: [Build a data feature in R]
tags: [time series,event detection,regression]
---

**The most important skill of any aspiring data professional is the abillity to make kick butt, automated data features (and ultimately, products).**  

This fact has given rise to what I'll dub here as the "full stack" data scientist. A full stack data scientist is someone comfortable with building the entire data product "circuit" him/herself. At a high level, this entails a command of comfort in building data pipelines, synthesizing readable code-bases, employing relevant statistical/machine learning paradigms, and interacting with an appropriate database that can empower the delivery of value that you ultimately want to produce.

In this 3 part series I will outline my approach & methodology to building a micro service-based data feature that we are using at [Atomata](https://growatomata.com) today, for work with time series data streams to optimize indoor environments for cannabis cultivation. I hope the process can be informative at all steps, but feel free to skip around. I'll be writing to this mini-series over the upcoming weeks as time permits.  

1. **Define your motivation, do your research (& eat your vegetables).**
2. **Getting in bed with an algorithm & take charge**
3. **Take it live!**

<center>*(Feat. R & Friends.)*</center>